version: '3.8'
services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./server/.env
    networks:
      - sprintflow
    ports:
      - 8080:8080

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - sprintflow
    ports:
      - 80:80 # Serve frontend on port 80 (HTTP default)
    depends_on:
      - api

networks:
  sprintflow:
    driver: bridge